name: Notebook Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run once a week on Monday at 00:00 UTC
    - cron: '0 0 * * 1'
  workflow_dispatch:
    # Manual trigger

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test notebooks with pytest-nbmake
      run: |
        python -m pytest --nbmake notebooks/

    - name: Test Python modules
      run: |
        python -m pytest tests/
