name: Notebook Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]  # Run on PRs from any branch
  schedule:
    # Run once a week on Monday at 00:00 UTC
    - cron: '0 0 * * 1'
  workflow_dispatch:
    # Manual trigger

jobs:
  test:
    runs-on: ubuntu-latest
    # Explicitly name the job to match branch protection rule
    name: Notebook Tests

    strategy:
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    # Explicitly report early status
    - name: Initialize Status Check
      run: echo "Starting notebook tests - this will block merges until completed"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test notebooks with pytest-nbmake
      run: |
        python -m pytest --nbmake notebooks/

    - name: Test Python modules
      run: |
        python -m pytest tests/

    - name: Tests completed
      run: |
        echo "All notebook tests completed successfully"
